// Export all slice reducers
export { default as authReducer } from './authSlice';
export { default as userReducer } from './userSlice';
export { default as propertyReducer } from './propertySlice';
export { default as walletReducer } from './walletSlice';
export { default as notificationReducer } from './notificationSlice';
export { default as themeReducer } from './themeSlice';

// Export all actions from authSlice
export {
  login,
  register,
  logout,
  refreshToken,
  verifyToken,
  setUser,
  updateUser,
  clearError,
  resetAuth,
  selectAuth,
  selectIsAuthenticated,
  selectUser,
  selectAuthLoading,
  selectAuthError,
  selectToken,
} from './authSlice';

// Export all actions from userSlice
export {
  fetchUserProfile,
  updateUserProfile,
  fetchUserStats,
  fetchRankProgress,
  fetchKYCDocuments,
  uploadKYCDocument,
  fetchBankAccounts,
  addBankAccount,
  updateBankAccount,
  setPrimaryBankAccount,
  updateProfile,
  updateStats,
  clearUserError,
  resetUser,
  selectUserProfile,
  selectUserStats,
  selectRankProgress,
  selectKYCDocuments,
  selectBankAccounts,
  selectPrimaryBankAccount,
  selectUserLoading,
  selectStatsLoading,
  selectRankProgressLoading,
  selectUserError,
} from './userSlice';

// Export all actions from propertySlice
export {
  fetchProperties,
  fetchPropertyById,
  fetchFeaturedProperties,
  fetchNewLaunchProperties,
  searchProperties,
  setFilters,
  clearFilters,
  setSearchQuery,
  clearSearchQuery,
  setSelectedProperty,
  setCurrentPage as setPropertyPage,
  setPageSize as setPropertyPageSize,
  setViewMode,
  setSortBy,
  clearPropertyError,
  resetPropertyState,
  selectProperties,
  selectSelectedProperty,
  selectPropertyFilters,
  selectSearchQuery,
  selectViewMode,
  selectSortBy,
  selectCurrentPage as selectPropertyCurrentPage,
  selectPageSize as selectPropertyPageSize,
  selectTotalProperties,
  selectTotalPages as selectPropertyTotalPages,
  selectPropertyLoading,
  selectSelectedPropertyLoading,
  selectPropertyError,
} from './propertySlice';

// Export all actions from walletSlice
export {
  fetchWalletBalance,
  fetchTransactions,
  fetchTransactionById,
  fetchWithdrawals,
  fetchWithdrawalRules,
  requestWithdrawal,
  cancelWithdrawal,
  transferFunds,
  setSelectedWalletType,
  setTransactionFilters,
  clearTransactionFilters,
  setCurrentPage as setWalletPage,
  setPageSize as setWalletPageSize,
  updateBalance,
  clearWalletError,
  resetWallet,
  selectWalletBalance,
  selectTransactions,
  selectWithdrawals,
  selectSelectedWalletType,
  selectTransactionFilters,
  selectTransactionSummary,
  selectWithdrawalRules,
  selectTotalTransactions,
  selectCurrentPage as selectWalletCurrentPage,
  selectPageSize as selectWalletPageSize,
  selectTotalPages as selectWalletTotalPages,
  selectWalletLoading,
  selectTransactionsLoading,
  selectWithdrawalsLoading,
  selectWalletError,
} from './walletSlice';

// Export all actions from notificationSlice
export {
  fetchNotifications,
  fetchUnreadCount,
  markAsRead,
  markAllAsRead,
  deleteNotification,
  deleteAllNotifications,
  fetchNotificationSettings,
  updateNotificationSettings,
  fetchAnnouncements,
  addNotification,
  removeNotification,
  markNotificationAsRead,
  setCurrentPage as setNotificationPage,
  setPageSize as setNotificationPageSize,
  clearNotificationError,
  resetNotifications,
  selectNotifications,
  selectUnreadNotifications,
  selectUnreadCount,
  selectAnnouncements,
  selectPinnedAnnouncements,
  selectNotificationSettings,
  selectTotalNotifications,
  selectCurrentPage as selectNotificationCurrentPage,
  selectPageSize as selectNotificationPageSize,
  selectTotalPages as selectNotificationTotalPages,
  selectNotificationLoading,
  selectSettingsLoading,
  selectNotificationError,
} from './notificationSlice';

// Export all actions from themeSlice
export {
  setThemeMode,
  toggleThemeMode,
  setColorScheme,
  setFontSize,
  toggleSidebar,
  setSidebarCollapsed,
  setCompactMode,
  toggleCompactMode,
  setAnimationsEnabled,
  toggleAnimations,
  setHighContrast,
  toggleHighContrast,
  resetThemeSettings,
  initializeTheme,
  selectThemeMode,
  selectEffectiveThemeMode,
  selectColorScheme,
  selectFontSize,
  selectSidebarCollapsed,
  selectCompactMode,
  selectAnimationsEnabled,
  selectHighContrast,
  selectThemeSettings,
} from './themeSlice';

// Export types
export type { ThemeMode, ColorScheme, FontSize } from './themeSlice';
