// Export all RTK Query services
export { authService } from './authService';
export { propertyService } from './propertyService';
export { walletService } from './walletService';

// Export all hooks from authService
export {
  useLoginMutation,
  useRegisterMutation,
  useLogoutMutation,
  useRefreshTokenMutation,
  useVerifyTokenQuery,
  useLazyVerifyTokenQuery,
  useValidateSponsorQuery,
  useLazyValidateSponsorQuery,
  useSendOTPMutation,
  useVerifyOTPMutation,
  useForgotPasswordMutation,
  useResetPasswordMutation,
  useChangePasswordMutation,
  useVerifyEmailMutation,
  useVerifyMobileMutation,
  useEnable2FAMutation,
  useVerify2FAMutation,
  useDisable2FAMutation,
  useCheckEmailAvailabilityQuery,
  useLazyCheckEmailAvailabilityQuery,
  useCheckMobileAvailabilityQuery,
  useLazyCheckMobileAvailabilityQuery,
  useCheckUserIdAvailabilityQuery,
  useLazyCheckUserIdAvailabilityQuery,
  useResendVerificationEmailMutation,
  useResendVerificationSMSMutation,
} from './authService';

// Export all hooks from propertyService
export {
  useGetPropertiesQuery,
  useLazyGetPropertiesQuery,
  useSearchPropertiesMutation,
  useGetPropertyByIdQuery,
  useLazyGetPropertyByIdQuery,
  useGetFeaturedPropertiesQuery,
  useGetNewLaunchPropertiesQuery,
  useGetTrendingPropertiesQuery,
  useGetPropertiesByCategoryQuery,
  useLazyGetPropertiesByCategoryQuery,
  useGetPropertiesByTypeQuery,
  useLazyGetPropertiesByTypeQuery,
  useGetPropertiesByCityQuery,
  useLazyGetPropertiesByCityQuery,
  useGetSimilarPropertiesQuery,
  useLazyGetSimilarPropertiesQuery,
  useGetPropertyDocumentsQuery,
  useGetPropertyInvestmentsQuery,
  useAddToWishlistMutation,
  useRemoveFromWishlistMutation,
  useGetWishlistPropertiesQuery,
  useTrackPropertyViewMutation,
  useGetPropertyStatsQuery,
  useGetAvailableCitiesQuery,
  useGetPropertyTypesQuery,
  useGetPropertyAmenitiesQuery,
  useCalculateROIMutation,
  useGetPriceHistoryQuery,
} from './propertyService';

// Export all hooks from walletService
export {
  useGetWalletBalanceQuery,
  useGetWalletBalanceByTypeQuery,
  useGetTransactionsMutation,
  useGetTransactionByIdQuery,
  useGetRecentTransactionsQuery,
  useGetTransactionSummaryQuery,
  useGetWithdrawalsQuery,
  useGetWithdrawalByIdQuery,
  useGetWithdrawalRulesQuery,
  useRequestWithdrawalMutation,
  useCancelWithdrawalMutation,
  useTransferFundsMutation,
  useVerifyTransactionPinMutation,
  useSetTransactionPinMutation,
  useChangeTransactionPinMutation,
  useResetTransactionPinMutation,
  useGetWalletStatsQuery,
  useGetWalletActivityQuery,
  useExportTransactionsMutation,
  useGetTransactionReceiptQuery,
  useLazyGetTransactionReceiptQuery,
  useGetWithdrawalReceiptQuery,
  useLazyGetWithdrawalReceiptQuery,
  useGetAvailableBalanceQuery,
  useCalculateWithdrawalMutation,
} from './walletService';
