/// Tree node model representing a user in the MLM binary tree structure
class TreeNodeModel {
  /// Unique identifier for the tree node
  final String id;

  /// User ID
  final String userId;

  /// User's full name
  final String userName;

  /// URL to user's profile picture
  final String? profilePicture;

  /// User's current rank
  final String rank;

  /// Position in parent's tree (left, right, root)
  final String position;

  /// Level/depth in the tree (0 for root)
  final int level;

  /// Left child node
  final TreeNodeModel? leftChild;

  /// Right child node
  final TreeNodeModel? rightChild;

  /// Number of direct referrals
  final int directReferrals;

  /// Total team size under this node
  final int teamSize;

  /// Business volume generated by this user and their team
  final double businessVolume;

  /// User account status (active, inactive, suspended)
  final String status;

  const TreeNodeModel({
    required this.id,
    required this.userId,
    required this.userName,
    required this.rank, required this.position, required this.level, required this.directReferrals, required this.teamSize, required this.businessVolume, required this.status, this.profilePicture,
    this.leftChild,
    this.rightChild,
  });

  /// Creates a TreeNodeModel instance from a JSON map
  factory TreeNodeModel.fromJson(Map<String, dynamic> json) {
    return TreeNodeModel(
      id: json['id'] as String,
      userId: json['userId'] as String,
      userName: json['userName'] as String,
      profilePicture: json['profilePicture'] as String?,
      rank: json['rank'] as String,
      position: json['position'] as String,
      level: json['level'] as int,
      leftChild: json['leftChild'] != null
          ? TreeNodeModel.fromJson(json['leftChild'] as Map<String, dynamic>)
          : null,
      rightChild: json['rightChild'] != null
          ? TreeNodeModel.fromJson(json['rightChild'] as Map<String, dynamic>)
          : null,
      directReferrals: json['directReferrals'] as int,
      teamSize: json['teamSize'] as int,
      businessVolume: (json['businessVolume'] as num).toDouble(),
      status: json['status'] as String,
    );
  }

  /// Converts the TreeNodeModel instance to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'userName': userName,
      'profilePicture': profilePicture,
      'rank': rank,
      'position': position,
      'level': level,
      'leftChild': leftChild?.toJson(),
      'rightChild': rightChild?.toJson(),
      'directReferrals': directReferrals,
      'teamSize': teamSize,
      'businessVolume': businessVolume,
      'status': status,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is TreeNodeModel &&
        other.id == id &&
        other.userId == userId &&
        other.userName == userName &&
        other.profilePicture == profilePicture &&
        other.rank == rank &&
        other.position == position &&
        other.level == level &&
        other.leftChild == leftChild &&
        other.rightChild == rightChild &&
        other.directReferrals == directReferrals &&
        other.teamSize == teamSize &&
        other.businessVolume == businessVolume &&
        other.status == status;
  }

  @override
  int get hashCode {
    return Object.hash(
      id,
      userId,
      userName,
      profilePicture,
      rank,
      position,
      level,
      leftChild,
      rightChild,
      directReferrals,
      teamSize,
      businessVolume,
      status,
    );
  }
}
