import React, { useState, useEffect } from 'react';
import {
    Card,
    Table,
    Tag,
    Typography,
    DatePicker,
    Space,
    Button,
    message
} from 'antd';
import { DownloadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import api from '../../api/axiosConfig';

const { Title } = Typography;
const { RangePicker } = DatePicker;

const LevelIncomeReport: React.FC = () => {
    const [loading, setLoading] = useState(false);
    const [data, setData] = useState([]);
    const [pagination, setPagination] = useState({ current: 1, pageSize: 10, total: 0 });
    const [dateRange, setDateRange] = useState<any>(null);

    const fetchTransactions = async (page = 1, dates = dateRange) => {
        setLoading(true);
        try {
            const params: any = {
                page,
                limit: pagination.pageSize,
                type: 'LEVEL_COMMISSION', // Filter by Level Commission
            };

            if (dates) {
                params.startDate = dates[0].format('YYYY-MM-DD');
                params.endDate = dates[1].format('YYYY-MM-DD');
            }

            // Assuming admin has an endpoint to fetch all commissions
            const response = await api.get('/commissions/history', { params });

            if (response.data.success) {
                // Ensure data is always an array
                const commissionsData = Array.isArray(response.data.data) ? response.data.data : [];
                setData(commissionsData);
                setPagination({
                    ...pagination,
                    current: page,
                    total: response.data.pagination.total
                });
            } else {
                setData([]); // Set empty array if no data
            }
        } catch (error) {
            console.error(error);
            message.error('Failed to fetch level income report');
            setData([]); // Set empty array on error
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchTransactions();
    }, []);

    const handleTableChange = (pag: any) => {
        fetchTransactions(pag.current);
    };

    const handleDateChange = (dates: any) => {
        setDateRange(dates);
        fetchTransactions(1, dates);
    };

    const columns = [
        {
            title: 'Date',
            dataIndex: 'createdAt',
            key: 'createdAt',
            render: (text: string) => dayjs(text).format('DD MMM YYYY HH:mm'),
        },
        {
            title: 'Beneficiary (Upline)',
            dataIndex: 'user', // Assuming populated
            key: 'user',
            render: (user: any) => user ? `${user.firstName} ${user.lastName} (${user.username})` : '-',
        },
        {
            title: 'Generated By (Downline)',
            dataIndex: 'fromUser',
            key: 'fromUser',
            render: (user: any) => user ? `${user.firstName} ${user.lastName} (${user.username})` : '-',
        },
        {
            title: 'Level',
            dataIndex: 'level',
            key: 'level',
            render: (level: number) => <Tag color="blue">Level {level}</Tag>,
        },
        {
            title: 'Booking Amount',
            dataIndex: 'baseAmount',
            key: 'baseAmount',
            render: (val: string) => `₹${parseFloat(val).toLocaleString()}`,
        },
        {
            title: 'Commission %',
            dataIndex: 'percentage',
            key: 'percentage',
            render: (val: string) => `${val}%`,
        },
        {
            title: 'Commission Paid',
            dataIndex: 'amount',
            key: 'amount',
            render: (val: string) => <span style={{ color: 'green', fontWeight: 'bold' }}>₹{parseFloat(val).toLocaleString()}</span>,
        },
        {
            title: 'Status',
            dataIndex: 'status',
            key: 'status',
            render: (status: string) => (
                <Tag color={status === 'EARNED' || status === 'PAID' ? 'success' : 'default'}>
                    {status}
                </Tag>
            ),
        },
    ];

    return (
        <Card>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                <Title level={4}>Level Income Report</Title>
                <Space>
                    <RangePicker onChange={handleDateChange} />
                    <Button icon={<DownloadOutlined />}>Export</Button>
                </Space>
            </div>

            <Table
                columns={columns}
                dataSource={data}
                rowKey="id"
                pagination={pagination}
                loading={loading}
                onChange={handleTableChange}
            />
        </Card>
    );
};

export default LevelIncomeReport;
